### ISSUE TITLE
Question about computing kernel

### ISSUE THREAD

**Issue by BinWang28** [autoliuweijie/BERT-whitening-pytorch#4]
https://github.com/autoliuweijie/BERT-whitening-pytorch/blob/f52f7c34c7c1a1b409ff9c0d59d3fa02958ee83a/all_utils.py#L72

Thanks for public the code. May I ask why taking the inverse step? There seems no inverse in the paper and the TensorFlow version (https://github.com/bojone/BERT-whitening)?

**Comment by autoliuweijie** [comment]
谢谢您指出，并提交修改
